### ISSUE TITLE
`sigmoid` is not implemented efficiently

### ISSUE THREAD

**Issue by JamorMoussa** [JamorMoussa/NanoTorch#19]
### Issue:
For further information check the following article, titled **Sigmoid and Softmax Are Not Implemented the Way Most People Think**: 

[Sigmoid and Softmax Are Not Implemented the Way Most People Think](https://blog.dailydoseofds.com/p/sigmoid-and-softmax-are-not-implemented)

**Comment by JamorMoussa** [comment]
Hey @JaouadT, After testing the implementation got the following error:

```bash
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moussa/Documents/programming/NanoTorch/nanotorch/nn/base.py", line 79, in forward
    return self.active_func(input)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moussa/Documents/programming/NanoTorch/nanotorch/utils/_decorators/dtype.py", line 15, in wrapper
    return func(input)
           ^^^^^^^^^^^
  File "/home/moussa/Documents/programming/NanoTorch/nanotorch/nn/functional.py", line 17, in sigmoid
    if input > 0:
       ^^^^^^^^^
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
➜  NanoTo
```

I quickly merged without testing, I thought that implementation would work in my knowledge, but after asking ChatGPT, he gives me :

```python
@input_as(DType = Tensor)
def sigmoid(input: Tensor) -> Tensor:
    return np.where(input > 0, 1/(1 + np.exp(-input)), np.exp(input)/(1 + np.exp(input)))
```

you can use `where` which is defined in the `nanotorch.where` instead of `numpy.where`, to insure the output is `Tensor` type.

**Comment by JamorMoussa** [comment]
I think that the first condition will execute in all case

```python
@input_as(DType = Tensor)
def sigmoid(input: Tensor)-> Tensor:
    if np.where(input > 0 ):
        return Tensor(1/(1 + np.exp(-input)))
    else:
        return Tensor(np.exp(input)/(1 + np.exp(input)))
```

while `np.where(input > 0 )` not `None` or `0`. 

I think the correct implementation is 

```python 
@input_as(DType = Tensor)
def sigmoid(input: Tensor) -> Tensor:
    return np.where(input > 0, 1/(1 + np.exp(-input)), np.exp(input)/(1 + np.exp(input)))
```

**Comment by JaouadT** [comment]
Yes, it will execute in all cases, but when you have a very large number you will get the overflow warning.

**Comment by JamorMoussa** [comment]
Yes, that happens because in Python when using the `if` statement with any Python object that doesn't return a `None` value it will be considered as `True`. The `np.where(input > 0 )` return a object, so `if np.where(input > 0 ):` will be `True` all time. Then, the first `Tensor(1/(1 + np.exp(-input)))` will be used whichever the `input` is. This for large number give overflow warnings.

**Comment by JamorMoussa** [comment]
Hey @anas1IA  @JaouadT  even the implementation, I have suggested  

```python
@input_as(DType = Tensor)
def sigmoid(input: Tensor) -> Tensor:
    return np.where(input > 0, 1/(1 + np.exp(-input)), np.exp(input)/(1 + np.exp(input)))
```

gives the overflow runtime warning. But, I got another alternative using `tanh` : 

$$
\sigma(x) = \frac{1}{1 + e^{-x}} = \frac{1}{2}(1 + \tanh(\frac{x}{2}))
$$

```python
@input_as(DType = Tensor)
def sigmoid(input: Tensor)-> Tensor:
    return Tensor(0.5 * (1 + np.tanh(0.5 * input)))
```

this implementation fixes the overflow runtime warning.
